#!/bin/bash
COMMIT_MSG="looping" ; 
while [ "${COMMIT_MSG}" != "q" ]; do 
    clear ; 
    echo "${COMMIT_MSG}"; 
    git commit -a -m "${COMMIT_MSG}" && git push && wd deploy --to=loki; 
    echo -n "Commit: "; 
    OLD="${COMMIT_MSG}"; 
    read COMMIT_MSG; 
    [ -z "${COMMIT_MSG}" ] && COMMIT_MSG="${OLD}"; 
done
