test: system jarvis berry crunchy
	perl -MYAML -le 'YAML::LoadFile("system");'
	perl -MYAML -le 'YAML::LoadFile("jarvis");'
	perl -MYAML -le 'YAML::LoadFile("crunchy");'
	perl -MYAML -le 'YAML::LoadFile("berry");'
